In [ ]:
# Week 1: Pandas Series and Data Frames (Prep for 9/29)

In [4]:
# Pandas and NumPy are Python packages to wrangle and analyze tabular data

# Important note: Always import all of the packages in a single cell at the top of your notebook.

import pandas as pd 
import numpy as np

In [ ]:
# Series: One-dimensional array of indexed data.

In [5]:
# A numpy array
arr = np.random.randn(4) # random values from std normal distribution
print(type(arr))
print(arr, "\n")

# A pandas series made from the previous array
s = pd.Series(arr)
print(type(s))
print(s)

<class 'numpy.ndarray'>
[-0.07256294 -0.92057058  0.64782059  0.17366843]

<class 'pandas.core.series.Series'>
0   -0.072563
1   -0.920571
2    0.647821
3    0.173668
dtype: float64

In [ ]:
# The index is printed as part of the pandas.Series while, the np.array is still indexable, the index is not part of this data structure. 
# Printing the pandas.Series also shows the values and their data type.

In [ ]:
# Creating a pandas.Series

In [ ]:
# Basic structure: pd.Series(data, index=index)
# Data could be a NumPy array, Python dictionary, single number, string, or boolean
# Index: The index parameter is optional. If included, it must be a list of indices of the same length as data

In [7]:
# A series from a numpy array 
pd.Series(np.arange(3), index=[2023, 2024, 2025])

2023    0
2024    1
2025    2
dtype: int64

In [8]:
# A series from a list of strings with default index
pd.Series(['EDS 220', 'EDS 222', 'EDS 223', 'EDS 242'])

0    EDS 220
1    EDS 222
2    EDS 223
3    EDS 242
dtype: object

In [ ]:
# Creating a pandas.Series from a dictionary

In [9]:
# Construct dictionary
d = {'key_0':2, 'key_1':'3', 'key_2':5}

# Initialize series using a dictionary
pd.Series(d)

key_0    2
key_1    3
key_2    5
dtype: object

In [ ]:
# Creating a pandas.Series from a single value (need to provide an index so the value that is being repeated matches the length of the index)

In [10]:
pd.Series(3.0, index = ['A', 'B', 'C'])

A    3.0
B    3.0
C    3.0
dtype: float64

In [ ]:
# Simple Operations

In [11]:
# Define a series
s = pd.Series([98,73,65],index=['Andrea', 'Beth', 'Carolina'])

# Divide each element in series by 10
print(s /10, '\n')

# Take the exponential of each element in series
print(np.exp(s), '\n')

# Original series is unchanged
print(s)

Andrea      9.8
Beth        7.3
Carolina    6.5
dtype: float64

Andrea      3.637971e+42
Beth        5.052394e+31
Carolina    1.694889e+28
dtype: float64

Andrea      98
Beth        73
Carolina    65
dtype: int64

In [12]:
s > 70

Andrea       True
Beth         True
Carolina    False
dtype: bool

In [ ]:
# Identifying missing values: represent a missing, NULL or NA with the float value numpy.nan

In [13]:
# Series with NAs in it
s = pd.Series([1, 2, np.nan, 4, np.nan])
s

0    1.0
1    2.0
2    NaN
3    4.0
4    NaN
dtype: float64

In [15]:
# Check if series has NAs with hasnans attribute
s.hasnans

True

In [14]:
# After detecting NA values, know which elements in the series are NAs with the isna method
s.isna()

0    False
1    False
2     True
3    False
4     True
dtype: bool

In [ ]:
# CHECK-IN: The integer number -999 is often used to represent missing values. Create a pandas.Series named s with four integer values, two of which are -999. 
# The index of this series should be the letters A through D.

In [17]:
s = pd.Series([-999, 4, -999, 8], index=['A', 'B', 'C', 'D'])

In [18]:
s

A   -999
B      4
C   -999
D      8
dtype: int64

In [ ]:
# CHECK-IN: In the pandas.Series documentation, look for the method mask(). Use this method to update the series s so that the -999 values are replaced by NA values.

In [20]:
s.mask(s<0)

A    NaN
B    4.0
C    NaN
D    8.0
dtype: float64

In [ ]:
# Data Frames (each column of a pandas.DataFrame is a pandas.Series)

In [ ]:
# Example way to make a pandas dataframe

In [21]:
# Initialize dictionary with columns' data 
d = {'col_name_1' : pd.Series(np.arange(3)),
     'col_name_2' : pd.Series([3.1, 3.2, 3.3]),
     }

# Create data frame
df = pd.DataFrame(d)
df

   col_name_1  col_name_2
0           0         3.1
1           1         3.2
2           2         3.3

In [22]:
# change the index by changing the index attribute
# Change index
df.index = ['a','b','c']
df

   col_name_1  col_name_2
a           0         3.1
b           1         3.2
c           2         3.3

In [ ]:
# CHECK-IN: We can access the data frame’s column names via the columns attribute. Update the column names to C1 and C2 by updating this attribute.

In [24]:
df.columns = ['C1', 'C2']
df

   C1   C2
a   0  3.1
b   1  3.2
c   2  3.3

In [ ]:
# Summary of lesson: reviewed the basics of the NumPy and Pandas Python packages